---
language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '7.1'
  - '7.2'

matrix:
  fast_finish: true
  include:
#    - php: 7.1
#      env: SYMFONY_VERSION=3.4 COVERAGE=true
#    - php: 7.1
#      env: SYMFONY_VERSION=2.8.*
#    - php: 7.1
#      env: SYMFONY_VERSION=3.0.*
#    - php: 7.1
#      env: SYMFONY_VERSION=3.1*
#    - php: 7.1
#      env: SYMFONY_VERSION=3.2.*
#    - php: 7.1
#      env: SYMFONY_VERSION=3.3.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
#    - php: 7.1
#      env: SYMFONY_VERSION=4.0.*
#    - php: 7.2
#      env: SYMFONY_VERSION=2.8.*
#    - php: 7.2
#      env: SYMFONY_VERSION=3.0.*
#    - php: 7.2
#      env: SYMFONY_VERSION=3.1*
#    - php: 7.2
#      env: SYMFONY_VERSION=3.2.*
#    - php: 7.2
#      env: SYMFONY_VERSION=3.3.*
#    - php: 7.2
#      env: SYMFONY_VERSION=3.4.*
#    - php: 7.2
#      env: SYMFONY_VERSION=4.0.*

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

phpunit: if [ "$COVERAGE" == true ]; then phpunit --coverage-text; else phpunit; fi

# After a build, send email notification with the build results
notifications:
  email: contax@phrenetic.org
